### ISSUE TITLE
TypeError: 'map' object is not subscriptable

### ISSUE THREAD

**Issue by wuyong666666** [gwding/draw_convnet#1]
runfile('S:/draw_convnet-master/draw_convnet.py', wdir='S:/draw_convnet-master')
Traceback (most recent call last):

  File "<ipython-input-16-857f0935c717>", line 1, in <module>
    runfile('S:/draw_convnet-master/draw_convnet.py', wdir='S:/draw_convnet-master')

  File "C:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 89, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "S:/draw_convnet-master/draw_convnet.py", line 128, in <module>
    num=num_show_list[ind],

TypeError: 'map' object is not subscriptable

I use python 3.5.2

**Comment by gwding** [comment]
This is fixed in commit 77976218d6c9d7f8ed5b09c5fffb3f0610fd5e42
I tested with python 3.4.3
Let me know if it does not work.
